# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/ECE/ECE530/XUP/embedded/2015_2_zynq_labs/Lab10p1/Lab10p1.cache/wt [current_project]
set_property parent.project_path D:/ECE/ECE530/XUP/embedded/2015_2_zynq_labs/Lab10p1/Lab10p1.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:zybo:part0:1.0 [current_project]
set_property ip_repo_paths {
  d:/ECE/ECE530/XUP/embedded/2015_2_zynq_labs/Lab3OMS/led_ip_1.0
  d:/ECE/ECE530/XUP/embedded/2015_2_zynq_labs/ip_repo/zybo_base_system_lib
} [current_project]
add_files D:/ECE/ECE530/XUP/embedded/2015_2_zynq_labs/Lab10p1/Lab10p1.srcs/sources_1/bd/system/system.bd
set_property used_in_implementation false [get_files -all d:/ECE/ECE530/XUP/embedded/2015_2_zynq_labs/Lab10p1/Lab10p1.srcs/sources_1/bd/system/ip/system_processing_system7_0_1/system_processing_system7_0_1.xdc]
set_property used_in_implementation false [get_files -all d:/ECE/ECE530/XUP/embedded/2015_2_zynq_labs/Lab10p1/Lab10p1.srcs/sources_1/bd/system/ip/system_axi_vdma_0_0/system_axi_vdma_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/ECE/ECE530/XUP/embedded/2015_2_zynq_labs/Lab10p1/Lab10p1.srcs/sources_1/bd/system/ip/system_axi_vdma_0_0/system_axi_vdma_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/ECE/ECE530/XUP/embedded/2015_2_zynq_labs/Lab10p1/Lab10p1.srcs/sources_1/bd/system/ip/system_axi_vdma_0_0/system_axi_vdma_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/ECE/ECE530/XUP/embedded/2015_2_zynq_labs/Lab10p1/Lab10p1.srcs/sources_1/bd/system/ip/system_rst_processing_system7_0_100M_1/system_rst_processing_system7_0_100M_1_board.xdc]
set_property used_in_implementation false [get_files -all d:/ECE/ECE530/XUP/embedded/2015_2_zynq_labs/Lab10p1/Lab10p1.srcs/sources_1/bd/system/ip/system_rst_processing_system7_0_100M_1/system_rst_processing_system7_0_100M_1.xdc]
set_property used_in_implementation false [get_files -all d:/ECE/ECE530/XUP/embedded/2015_2_zynq_labs/Lab10p1/Lab10p1.srcs/sources_1/bd/system/ip/system_rst_processing_system7_0_100M_1/system_rst_processing_system7_0_100M_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/ECE/ECE530/XUP/embedded/2015_2_zynq_labs/Lab10p1/Lab10p1.srcs/sources_1/bd/system/ip/system_xbar_1/system_xbar_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/ECE/ECE530/XUP/embedded/2015_2_zynq_labs/Lab10p1/Lab10p1.srcs/sources_1/bd/system/ip/system_auto_pc_4/system_auto_pc_4_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/ECE/ECE530/XUP/embedded/2015_2_zynq_labs/Lab10p1/Lab10p1.srcs/sources_1/bd/system/ip/system_auto_pc_5/system_auto_pc_5_ooc.xdc]
set_property used_in_implementation false [get_files -all D:/ECE/ECE530/XUP/embedded/2015_2_zynq_labs/Lab10p1/Lab10p1.srcs/sources_1/bd/system/system_ooc.xdc]
set_property is_locked true [get_files D:/ECE/ECE530/XUP/embedded/2015_2_zynq_labs/Lab10p1/Lab10p1.srcs/sources_1/bd/system/system.bd]

read_verilog -library xil_defaultlib D:/ECE/ECE530/XUP/embedded/2015_2_zynq_labs/Lab10p1/Lab10p1.srcs/sources_1/bd/system/hdl/system_wrapper.v
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/ECE/ECE530/XUP/embedded/2015_2_zynq_labs/Lab10p1/Lab10p1.srcs/constrs_1/imports/lab3/lab3_zybo.xdc
set_property used_in_implementation false [get_files D:/ECE/ECE530/XUP/embedded/2015_2_zynq_labs/Lab10p1/Lab10p1.srcs/constrs_1/imports/lab3/lab3_zybo.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top system_wrapper -part xc7z010clg400-1


write_checkpoint -force -noxdef system_wrapper.dcp

catch { report_utilization -file system_wrapper_utilization_synth.rpt -pb system_wrapper_utilization_synth.pb }
